apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/write-back-target: argocd
    argocd-image-updater.argoproj.io/image-list: my-image=mveyone/argocd-release
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/am-devops09/ARGOCD-GHA-AIU-Release.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
