apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api-app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-resources/applications/my-api-app.yaml
    repoURL: 'https://github.com/am-devops09/ARGOCD-GHA-AIU-Release.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false