apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-api-kustomize
  name: my-api-kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api-kustomize
  template:
    metadata:
      labels:
        app: my-api-kustomize
    spec:
      containers:
      - image: mveyone/argocd-release
        name: my-api-kustomize
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-kustomize
spec:
  type: NodePort
  selector:
    app: my-api-kustomize
  ports:
  - port: 80
    targetPort: 80
